### ISSUE TITLE
Stop the movement of all kinematic chain when a joint reaches its limit

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/kinematics-dynamics#164] opened 2018-10-09 08:46 UTC
In reference to https://github.com/roboticslab-uc3m/teo-bimanipulation/issues/3#issuecomment-405940694

**Comment by PeterBowman** [comment] 2018-10-09 08:50
Duplicate of #161?

**Comment by PeterBowman** [comment] 2018-10-09 08:59
Yeah, I'm pretty sure the motivation behind #161 was actually avoiding the kind of errors we observed in the teo-bimanipulation demo. @rsantos88 I'm going to close this one and mark that issue as high priority, too.

**Closed as duplicate by PeterBowman** 2018-10-09 08:59 UTC
Labels: duplicate

**Comment by rsantos88** [comment] 2018-10-09 09:02
Perfect!! I'll close it. Thanks
